### Zip and enumerate

In [1]:
fruits = ['apple', 'mango', 'banana', 'watermelon', 'pineapple']

In [2]:
for fruit in fruits: print(fruit)

apple
mango
banana
watermelon
pineapple


In [3]:
prices = [10,5,0.25,15,100]

In [4]:
for fruit,price in zip(fruits, prices): print(f"{fruit} costs ${price}")

apple costs $10
mango costs $5
banana costs $0.25
watermelon costs $15
pineapple costs $100


In [5]:
print("Fruits on our menu")
for idx, fruit in enumerate(fruits): print(f"{idx}. {fruit}")

Fruits on our menu
0. apple
1. mango
2. banana
3. watermelon
4. pineapple


### Comprehensions

#### Lists

In [6]:
nums = [i for i in range(10)]
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
nums = [i for i in range(10) if (i % 2 == 0 and i != 4)]
nums

[0, 2, 6, 8]

In [8]:
n = 59125
digits = [int(i) for i in str(n)]
digits

[5, 9, 1, 2, 5]

In [9]:
x = ["55", "33", "22", "11"]
type(x[0])

str

In [10]:
nums = list(map(int, x))
nums

[55, 33, 22, 11]

#### operator.itemgetter

In [11]:
x = [[1,2], [3,4], [5,6]]

In [12]:
import operator
f = operator.itemgetter(0) # declare a function

In [13]:
list(map(f, x))

[1, 3, 5]

In [14]:
fruit_list = [(f,p) for f,p in zip(fruits, prices)]
fruit_list

[('apple', 10),
 ('mango', 5),
 ('banana', 0.25),
 ('watermelon', 15),
 ('pineapple', 100)]

In [15]:
sorted(fruit_list) # sorts by fruit name by default

[('apple', 10),
 ('banana', 0.25),
 ('mango', 5),
 ('pineapple', 100),
 ('watermelon', 15)]

In [16]:
sorted(fruit_list, key = operator.itemgetter(1))

[('banana', 0.25),
 ('mango', 5),
 ('apple', 10),
 ('watermelon', 15),
 ('pineapple', 100)]

#### Dictionaries

In [17]:
fruit_to_idx = {fruit:idx for idx, fruit in enumerate(fruits)}
fruit_to_idx

{'apple': 0, 'mango': 1, 'banana': 2, 'watermelon': 3, 'pineapple': 4}

In [18]:
idx_to_fruit = {idx:fruit for idx, fruit in enumerate(fruits)}
idx_to_fruit

{0: 'apple', 1: 'mango', 2: 'banana', 3: 'watermelon', 4: 'pineapple'}

In [19]:
import itertools
from operator import itemgetter

In [20]:
grades = [('prajakta', 'A+'), ('ramu', 'B'), ('darshan','A+'),('dipam','F'), 
          ('dhaval','B'),('amba','F'),('adi', 'A+')]

In [21]:
grades = list(sorted(grades, key = itemgetter(1)))
grades[:3]

[('prajakta', 'A+'), ('darshan', 'A+'), ('adi', 'A+')]

In [22]:
for k,v in itertools.groupby(grades, key=itemgetter(1)):
    print(k,list(v))

A+ [('prajakta', 'A+'), ('darshan', 'A+'), ('adi', 'A+')]
B [('ramu', 'B'), ('dhaval', 'B')]
F [('dipam', 'F'), ('amba', 'F')]


In [23]:
g_dict = {k:list(map(f,v)) for k,v in itertools.groupby(grades, key=itemgetter(1))}
g_dict

{'A+': ['prajakta', 'darshan', 'adi'],
 'B': ['ramu', 'dhaval'],
 'F': ['dipam', 'amba']}

### * operator

In [24]:
print("Python is cool " * 4)

Python is cool Python is cool Python is cool Python is cool 


In [25]:
import numpy as np

In [26]:
def train():
    for epoch in range(10):
        # some calc here
        print("Finished epoch ", epoch)
        print("Loss for epoch:",np.random.randn())
        print("Acc for epoch: ", epoch * 5 + 24)
        print("=" * 40)

In [27]:
train()

Finished epoch  0
Loss for epoch: 0.6645265351166383
Acc for epoch:  24
Finished epoch  1
Loss for epoch: 0.30312125063609635
Acc for epoch:  29
Finished epoch  2
Loss for epoch: -1.7845080199123189
Acc for epoch:  34
Finished epoch  3
Loss for epoch: 1.0731260385338006
Acc for epoch:  39
Finished epoch  4
Loss for epoch: -1.3540613313149499
Acc for epoch:  44
Finished epoch  5
Loss for epoch: 1.3053427638725295
Acc for epoch:  49
Finished epoch  6
Loss for epoch: 0.14216200235743964
Acc for epoch:  54
Finished epoch  7
Loss for epoch: 0.6954911487595169
Acc for epoch:  59
Finished epoch  8
Loss for epoch: 1.2758721894620102
Acc for epoch:  64
Finished epoch  9
Loss for epoch: 0.4580167275138469
Acc for epoch:  69


In [28]:
a, *b, c = digits
a, b, c

(5, [9, 1, 2], 5)

In [29]:
def stupid_calc(a,b,c,d,e): return a + b - c * d / e

In [30]:
stupid_calc(*digits)

13.6

In [31]:
def var_arg(*args, **kwargs):
    for arg in args: print(f"Argument {arg} was passed")
    print(kwargs)

In [32]:
var_arg(1,2,3, name= 'dipam')

Argument 1 was passed
Argument 2 was passed
Argument 3 was passed
{'name': 'dipam'}



### Partials

In [33]:
def simple_interest(p,n,r = 0.01): return (p*n*r) / 100
simple_interest(1000, 3, 0.5)

15.0

In [34]:
from functools import partial

In [35]:
f = partial(simple_interest, 1000)
f(3, 0.5)

15.0

In [36]:
f2 = partial(simple_interest, p = 1000, r = 0.5)
f2(n = 3)

15.0

### Asserts

In [37]:
x = np.random.randn(5,3)

In [38]:
assert x.shape[1] == 3

In [39]:
assert x.shape[1] == 4, "No of cols != 3"

AssertionError: No of cols != 3

### Pathlib

In [40]:
from pathlib import Path

In [41]:
Path.cwd()

PosixPath('/Users/dipamvasani/Desktop/Desktop - Dipam’s MacBook Air/coding/Fancy-python')

In [42]:
file_path = Path('/Users/dipamvasani/Desktop/Fancy-python')

In [43]:
file_path.is_dir()

False

In [44]:
file_path.parent

PosixPath('/Users/dipamvasani/Desktop')

In [45]:
import os

In [47]:
Path('test_folder').mkdir(exist_ok=True)
os.chdir('test_folder/')

In [48]:
for i in range(30):
    os.mkdir(str(i))
    os.chdir(str(i))
    for j in range(1000):
        os.mkdir(str(j))
    os.chdir('/Users/dipamvasani/Desktop/article_images/Fancy-python/test_folder')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/dipamvasani/Desktop/article_images/Fancy-python/test_folder'

In [48]:
%%time
for root, dirs, files in os.walk('/Users/dipamvasani/Desktop/article_images/Fancy-python/test_folder'):
    root += '_is_root'

CPU times: user 281 ms, sys: 520 ms, total: 801 ms
Wall time: 818 ms


### Generators

In [49]:
def my_gen(x):
    for i in range(x): yield i

In [50]:
my_gen(10)

<generator object my_gen at 0x114a94c10>

In [51]:
next(iter(my_gen(10)))

0

In [52]:
nums = (i for i in range(10))

In [53]:
next(iter(nums))

0

In [54]:
5 in nums

True

In [55]:
for num in nums: print(num)

6
7
8
9


In [56]:
class Test:
    time = 0
    location = 'not defined'
    def __init__(self):
        pass
    def conduct():
        pass

In [57]:
t = Test()

In [58]:
list(dir(t))[-7:]

['__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'conduct',
 'location',
 'time']

In [59]:
'location' in dir(t)

True

In [60]:
hasattr(t, 'location')

True

In [61]:
isinstance(fruits, list)

True

### Cleaner constructor

In [62]:
import re, inspect

In [63]:
def store_attr(self, nms):
    mod = inspect.currentframe().f_back.f_locals
    for n in re.split(', *', nms): setattr(self, n, mod[n])

In [64]:
class Test:
    def __init__(self, color, size, shape, length):
        store_attr(self, 'color, size, shape, length')

In [65]:
t = Test('blue', 10, (5,5), 100)

In [66]:
t.color

'blue'

### Pipe

In [67]:
import numpy as np

In [68]:
a = np.random.randint(0,100, (25,25))

In [69]:
def crop(x): return x[2:4, 2:4]
def normalize(x): return (x - np.mean(x)) / np.std(x)
def augmentation(x): return x

In [70]:
def compose(*funcs):
    def _inner(x, *args, **kwargs):
        for f in funcs: x = f(x, *args, **kwargs)
        return x
    return _inner

In [71]:
augmentation(normalize(crop(a)))

array([[ 0.64560703,  0.35047239],
       [ 0.71939069, -1.71547011]])

In [72]:
pipe = compose(crop, normalize, augmentation)

In [73]:
pipe(a)

array([[ 0.64560703,  0.35047239],
       [ 0.71939069, -1.71547011]])

### Any, all

In [74]:
nums = [x for x in range(-5, 5)]
nums

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

In [75]:
all(x > 0 for x in nums)

False

In [76]:
any(x < 0 for x in nums)

True

### Multiple assignment

In [77]:
a = b = c = d = 1

In [78]:
a,b,c,d

(1, 1, 1, 1)

In [79]:
a = 5

In [80]:
a,b,c,d

(5, 1, 1, 1)

### Callable

In [81]:
a = 5

In [82]:
def add(x,y): return x+y

In [83]:
callable(a)

False

In [84]:
callable(add)

True

### 2 loops in one line

In [85]:
from itertools import product

In [86]:
a = np.random.randint(0, 100, (3,3)); a

array([[ 6, 22, 29],
       [81,  3, 87],
       [ 9, 84,  6]])

In [87]:
for i,j in product(range(a.shape[0]), range(a.shape[1])):
    print(i, j, a[i,j])

0 0 6
0 1 22
0 2 29
1 0 81
1 1 3
1 2 87
2 0 9
2 1 84
2 2 6


### Flatten lists

In [88]:
nums = [[1], [2,3,4], [5,6,7]]

In [89]:
sum(nums, [])

[1, 2, 3, 4, 5, 6, 7]

In [90]:
too_nested = [[[[1,2], [3], [4,5], [6]]]]

In [91]:
while True: 
    too_nested = sum(too_nested, [])
    if not isinstance(too_nested[0], list): break

In [92]:
too_nested

[1, 2, 3, 4, 5, 6]

### Default dicts

In [93]:
from collections import defaultdict
import operator

In [94]:
depts = [('DS', 'dipam'), ('CS','ramu'), ('DS','prajakta'), ('IS','amba'), ('CS','adi')]

In [95]:
d = defaultdict(list)
for k,v in depts:
    d[k].append(v)
d.items()

dict_items([('DS', ['dipam', 'prajakta']), ('CS', ['ramu', 'adi']), ('IS', ['amba'])])

In [96]:
s = 'mississippi'
d = defaultdict(int)
for k in s:
    d[k] += 1
sorted(d.items(), key = operator.itemgetter(1), reverse = True)

[('i', 4), ('s', 4), ('p', 2), ('m', 1)]

### Delegation

In [97]:
import inspect

In [98]:
def delegates(to=None, keep=False):
    "Decorator: replace `**kwargs` in signature with params from `to`"
    def _f(f):
        if to is None: to_f,from_f = f.__base__.__init__,f.__init__
        else:          to_f,from_f = to,f
        sig = inspect.signature(from_f)
        sigd = dict(sig.parameters)
        k = sigd.pop('kwargs')
        s2 = {k:v for k,v in inspect.signature(to_f).parameters.items()
              if v.default != inspect.Parameter.empty and k not in sigd}
        sigd.update(s2)
        if keep: sigd['kwargs'] = k
        from_f.__signature__ = sig.replace(parameters=sigd.values())
        return f
    return _f

In [99]:
class Shape:
    def __init__(self, color = 'black', is_3d = False): pass

In [100]:
class circle:
    def __init__(self, radius, **kwargs): pass

In [101]:
@delegates(Shape)
class square:
    def __init__(self, side, **kwargs): pass

In [102]:
circle?

In [103]:
# shows arguments of Shape instead of kwargs
square?

### __ all __

![test]('https://github.com/dipam7/Fancy-python/tree/master/images/all_imports.png')

### Map

In [1]:
import numpy as np

In [2]:
X_train = [1,2,3]
y_train = [0,0,1]

X_val = [1,4,5]
y_val = [0,1,0]

In [3]:
# longer version
X_train = np.array(X_train)
y_train = np.array(y_train)
X_val = np.array(X_val)
y_val = np.array(y_val)

In [4]:
X_train

array([1, 2, 3])

In [5]:
X_train = [1,2,3]
y_train = [0,0,1]

X_val = [1,4,5]
y_val = [0,1,0]

In [6]:
# shorter version
X_train, y_train, X_val, y_val = map(np.array, (X_train, y_train, X_val, y_val))

In [7]:
X_train

array([1, 2, 3])

# Fin